### ISSUE TITLE
Should bullet3 be built with double-precision floats by default?

### ISSUE THREAD

**Issue by schornakj** [ros-industrial-consortium/tesseract_ext#10]
@Levi-Armstrong suggested adding `-DUSE_DOUBLE_PRECISION:BOOL=ON` to the `CMAKE_CACHE_ARGS` in `bullet3/CMakeLists.txt` as a fix for an issue where small overlaps between collision geometry (on the order of ~1mm) were not being detected correctly.

Is there any reason to not enable the double-precision option by default?

There's [a separate issue with bullet3 itself](https://github.com/bulletphysics/bullet3/issues/2582) where it does not export the `-DUSE_DOUBLE_PRECISION` compile definition correctly. This would need to be fixed first since it causes `tesseract_collision` to fail to build.

**Comment by Levi-Armstrong** [comment]
Yea, lets currently add it tesseract collision compiler definition for the bullet target until bullet's cmake is fixed. I will update the docker so CI passes. Once the PR is up for tesseract_collision I will push the docker and merge both PR's at the same time.

**Comment by schornakj** [comment]
OK, I submitted [a new PR against Tesseract](https://github.com/ros-industrial-consortium/tesseract/pull/213) with the changes to the `tesseract_collision` compiler definitions.

**Comment by schornakj** [comment]
This has all been merged in so I'm going to close this issue.
