### ISSUE TITLE
Option for building without a network connection

### ISSUE THREAD

**Issue by schornakj** [ros-industrial-consortium/tesseract_ext#12]
Currently tesseract_ext checks for updated versions of Bullet and the other external projects every time I build my workspace. This is rather inconvenient when I'm making experimental changes directly on my robot, since it isn't always possible to get a wired internet connection e.g. if the robot is deployed offsite.

Is it possible to configure the Cmake [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html) function to gracefully continue with the currently-downloaded version of the package in question if a network connection isn't available?

**Comment by Levi-Armstrong** [comment]
I would update to leverage [UPDATE_DISCONNECTED](https://cmake.org/cmake/help/v3.5/module/ExternalProject.html) option. It would be good to create a cmake variable for this option which defaults to true, but it would allow user to change it when building if the upstream has changed and they want it to check.

**Comment by mpowelson** [comment]
Addressed in #23
